# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbingWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbingWallPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10)),
                ('climbing_wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ClimbingWall')),
            ],
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.IntegerField()),
                ('success', models.BooleanField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Boulder')),
            ],
        ),
        migrations.AddField(
            model_name='boulder',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ClimbingWallPlace'),
        ),
    ]
